FROM node:8.15.0-stretch
WORKDIR /app
COPY ../../../../api/node_modules /node_modules
COPY ../../../../api/index.js /index.js
COPY ../../../../api/httpServer.js /httpServer.js
COPY ../../../../api/database.js /database.js
EXPOSE 8080
ENTRYPOINT ["node", "index.js"]
